- name: Scalr Automated Testing
  connection: local
  hosts: localhost
  sudo: true
  tasks:
# This Launches the Automated Testing farm
   - name: Launch Farm
     command: /usr/local/bin/scalr-ctl --config /tmp/testing_creds.yml farms list
     register: farmlaunch
     ignore_errors: True
