- name: Scalr Automated Testing
  connection: local
  hosts: localhost
  become: true
  vars_files:
   - vars.yml
  tasks:
# This Launches the Automated Testing farm
   - name: Launch Farm
     command: scalr-ctl --config /tmp/testing_creds.yml farms list
     environment:
      PATH: /usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/opt/scalr-server/embedded/bin/
     register: farmlaunch
     ignore_errors: True
