- name: Scalr Automated Testing
  connection: local
  hosts: localhost
  sudo: true
  tasks:
# This Launches the Automated Testing farm
   - name: Launch Farm
     environment:
      PATH: /usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin/scalr-ctl
     command: scalr-ctl --config /tmp/testing_creds.yml farms list
     register: farmlaunch
     ignore_errors: True
