- name: Scalr Automated Testing
  connection: local
  hosts: localhost
  vars_files:
   - vars.yml
  tasks:
# This Launches the Automated Testing farm
   - name: Launch Farm
     command: /usr/local/bin/scalr-ctl --config testing_creds.yml farms launch --envId {{env}} --farmId {{farm}}
     register: farmlaunch
     ignore_errors: True
